from http import client
from joshlib.ollama import OllamaClient
from joshlib.gemini import GeminiClient

prompt = """
You are a professional sermon editor. Your task is to write exactly ONE sentence describing the overall tone, mood, and delivery style of the sermon.

Instructions:
- Focus only on the preacher’s tone and style, such as solemn, joyful, urgent, reflective, passionate, or contemplative.
- Do NOT summarize the sermon content, give moral advice, or interpret theology.
- Do NOT include headings, labels, quotes, or any extra text.
- Write exactly ONE sentence.

Examples:
- "The sermon is delivered in a passionate and urgent tone, emphasizing the seriousness of repentance."
- "The sermon is reflective and contemplative, guiding the listener through a calm meditation on God’s grace."
- "The tone is joyful and celebratory, highlighting the hope and promise in God’s promises."

Sermon text:
---
{SERMON_TEXT}
"""

sermon = """
All right, well, thank you guys for the song. And by the way, that's part of our band, but we also have the Palmer part of our band as well. So if you want to come and hear us live and in concert, you can September 7th Sunday night at Simmons Grove Baptist Church.  

They're doing a series of Sunday evening meetings and we get to be the band. So we're going on the road or across the holler at least. We will have the full band with us.

All right, guys, we’re back in the book of Genesis this morning. Just to catch up, last week I had a special message on my heart and we looked at John chapter 3, but we’re returning to our series as we continue exploring the book of Genesis. So just to catch you up by way of review, in chapter 6, God sees the wickedness of man on the earth. Their numbers have multiplied, as has their wickedness, and God says, “My spirit shall not always strive with men; their days will be a hundred and twenty years.” We talked about how the wickedness of man was great in the earth, and that every thought and intention of his heart was only evil continually. And so God will destroy man whom He has created from the face of the earth, both man and beast, with a flood.

But Noah finds grace in the eyes of the Lord. Noah fears God. Noah walks with God. Noah is a righteous man. Noah acts with reverence and builds an ark to the saving of his family. We talked about how that ark represents the Lord Jesus Christ. There is one door in the ark, just as there is one way to heaven, one way to safety and salvation.  

And we looked at several other facts of the ark that are very interesting. So if you didn’t get to listen to that sermon, I highly encourage you to go back and listen to it.

But now we come to chapter 6. Verse 22 of chapter 6 says that Noah did according to all that he commanded. So he did. Noah built the ark according to God's blueprints and specifications. And now it's time for Noah and his family to enter the ark. Chapter 7, verse 1. And the Lord said to Noah, "Come into the ark, you and all your household, because I have seen that you are righteous before me in this generation." And you shall take with you seven of each of every clean animal, a male and his female, two each of animals that are unclean, a male and his female, also seven each of the birds of the air, male and female, to keep the species alive on the face of all the earth. For after seven more days I will cause it to rain on the earth. Forty days and forty nights, and I will destroy from the face of the earth all living things that I have made. Let’s keep that in mind.  

And Noah did according to all that the Lord commanded him. And Noah was 600 years old when the flood waters were on the earth. So Noah, along with his wife and the wives of his sons, and his sons, went into the ark because of the waters of the flood.

And he brings all the animals in. Verse 11 says, in the 600th year of Noah’s life, in the second month, on the 17th day of the month, on that day, all the fountains of the great deep were broken up, and the windows of heaven were opened. So we have water coming from above and water coming from below. And the rain was on the earth forty days and forty nights.  

On that same day, Noah and his sons—Shem, Ham, and Japheth—and Noah’s wife, along with the three wives of his sons, entered the ark. They, along with every beast after its kind, all the cattle after their kind, every creeping thing that creeps on the earth after its kind, and every bird after its kind, went into the ark. The Bible says they went into the ark, two by two, of all flesh that had the breath of life. So they entered, male and female of all flesh, as God had commanded him.

And underline this in your Bibles. The Lord shut the door. The Lord shut the door. Now we read that God warned Noah of this coming flood, but Noah still had to respond. Noah still had to believe. Noah still had to build the ark. Noah still had to enter into the ark with his family and with the animals. It was not enough just to know that judgment was coming. It was not enough just to have the blueprints of the ark. He had to obey. He had to build the ark. He had to step into the ark with his family and with the animals.  

In the same way, friends, salvation is God's work alone. He is sovereign over our salvation. You know my doctrine of salvation. You know I hold firmly to the doctrines of grace. God is sovereign in his election. God is sovereign in his choosing and in his drawing. But friends, we are also responsible to repent and to believe the gospel. Amen? God's sovereignty and human responsibility are two sides of the same coin. God doesn't drag us into the ark of salvation kicking and screaming against our wills. We still have to respond in obedience. We must repent. We must believe. We must obey his call to enter into the ark of salvation.

Now, God drew Noah and his family—and somehow, God also drew the animals. We don’t really know. The details are sparse, but God, in His infinite wisdom, knows how to fill the ark with animals. And they enter—this is where verse 16 comes in. God shut him in. Noah and his family have obeyed. They’ve entered the ark. The animals have come in, two by two. Seven pairs of clean animals, as God commanded. One pair of unclean animals. Everything is ready. The stage is set.

But think about what's going on outside of the ark. Outside the ark, the people are mocking. They're jeering. Who is this old man? He's 600 years old. The cheese has slid off the cracker. And to top it off, he's brought his family and all these animals. Where on earth are these animals coming from? And they're in this big wooden box and they laugh in disbelief and shake their heads, thinking what on earth is going on?  

That is until who shuts the door? Did Noah shut the door? Is there a rope on that thing? No. God shut the door. God shut the door. This massive door, likely weighing hundreds of pounds, slams shut. Not by Noah's hands, but by God's hands. It is sealed. It is final. They can't leave—not that they would want to—but also, no one else can get in. The time of repentance is over. The day of salvation has passed. The day of judgment has come.

And now the rains begin. Slowly at first, it comes as a sprinkle. The skies begin to grow darker. The clouds roll in. The drops turn to sheets of rain and it becomes a downpour, the ground becoming saturated. Suddenly, fountains of the deep burst forth, and massive geysers erupt from the earth. The canopy that's over the atmosphere opens up, dumping vast amounts of water on the earth. There is a deluge from above and below. That's when the panic begins to set in. That's when the scoffers begin to run. Some rush to higher ground. Others scramble up trees and rooftops. The waters continue to rise. Some of them think this crazy old man was right. He had been building this ark for 120 years. We thought he was a fool. They begin to pound on the door, but the door won't open. They plead. They scream. They scratch at the wood. It won't budge because God has shut the door.

The thunder roars in the heavens. The lightning flashes across the sky. Screams pierce the heavens. These mighty men, who have renown—these kings and giants—climb the mountains, but the floodwaters continue to chase them upward, and upward. Some people cling to trees and floating debris, but they're too weak to hold on. Mudslides swallow most people instantly. Others are drowned, but inside the ark there's Noah and his family. They are safe and secure, but no doubt the screams of panic and fear haunt them. They can feel the boat shift, rock, and sway back and forth. They can hear the pounding on the door before, but now they just hear the muddled screams of drowning people.  

And pretty soon they'll see floating corpses and they'll smell the stench of death, but they're in the ark. There's plenty of room for other people, but they mocked. They jeered. They were marrying, giving in marriage, eating, drinking, going about their day-to-day life, thinking a flood won't come. God won't punish us. The door was open for 120 years, but they refused to enter in.

Friends, this isn't just history. This is prophecy, because remember God promised to never destroy the earth with a flood, but as we reread 2nd Peter 3 a couple weeks ago, He promises to destroy the earth with fire. And there are people who mock the coming of the Lord, saying God won't bring judgment. You've been saying He's gonna return for nearly 2,000 years now. Where is He? There's another judgment coming, and another door will close. Today the door of salvation is open for whosoever will enter in, but one day it will close. And only those who are in the ark of safety will be spared, because this ark of safety, which is Christ, it is not only floodproof, but also fireproof as well.

Let's talk about the flood rising. Look at verse 17. The flood was on the earth 40 days, and the waters increased and lifted up the ark, and it rose high above the earth. The waters prevailed and greatly increased on the earth, and the ark moved about on the surface of the waters. Remember, it was built with precision. Engineers have even said that it is seaworthy by today's standards. Notice verse 19. The waters prevailed exceedingly high on the earth, and all the high hills under the whole heaven were covered. That means every single mountain on the face of the earth was covered with water. The reason why we believe in the global flood: the waters prevailed 15 cubits upward, and the mountains were covered.  

All flesh died that moved on the earth—birds and cattle and beasts and every creeping thing that creeps on the earth, and every man, all in whose nostrils was the breath of the spirit of life that God gave him, by the way, that was on the dry land—died. And he destroyed all living things which were on the face of the ground. Only Noah and those who were with him in the ark remained alive, and the waters prevailed on the earth 150 days.

Now, why do we as creationists believe in the global flood? Well, number one, I believe in the global flood because the Bible explicitly describes it as such. I believe in the plain rendering of the scriptures. Notice we read that all the high hills under the heaven were covered, and that the waters prevailed 15 cubits—equivalent to more than 20 feet—above the highest peak. Also in chapter 6, verses 13 and 17, God says, "I am about to destroy them with the earth. I will bring floodwaters on the earth to destroy how much? A few? Some? No, all of life under the heavens. All of life." This is a universal judgment affecting all land-dwelling, air-breathing life. Now, people ask me, "What about marine life and invertebrates?" Well, they would be safe in the water. They wouldn't need to be in the ark to survive. This is further supported in chapter 8, verses 5 through 9, where Noah sends out birds. They could find no dry land, indicating a total inundation of the earth—not merely a localized flood.

Also, we're going to talk about the duration of the flood. It lasted over a year. This is far longer than would be necessary for a localized regional flood, and we must also consider the size of the ark. Remember the ark's dimensions? 450 by 45 by 75. It was built to preserve all kinds of animals, not just the local ones, and this only makes sense in the context of a global flood.

But did you know there's also geological evidence pointing to a global flood? I've done some studying on this. I've done some ciphering, as the old people would say, and let me tell you, we are just scratching the surface. Once again, go home and read *Answers in Genesis*. They give you all kinds of articles, but here's some cool things I found. There are fossil layers across continents. These sedimentary rock layers span continents and even oceans. There's also rapid burial of organisms. There are mass fossil graveyards, like those in the Morrison Formation, in the Green River Formation, and they show signs of a rapid, watery burial—conditions expected in a global flood.  

It's also the lack of erosion between layers in sedimentary rock. They lack signs of long-term erosion between them, suggesting rapid deposition. And then there's also some polystrate fossils. These are trees and other fossils extending vertically, not horizontally, through multiple rock layers. This suggests these layers were laid down quickly, not over millions of years. Think about that. You have trees standing straight up. You have multiple sedimentary layers. Supposedly, each takes millions of years to form. Well, why is the tree in all of those? Because it happened quick. It happened instantly.

You know, they've also found dinosaurs. Paleontologists have discovered fossilized dinosaurs in strikingly lifelike positions. For example, there's a Pythocasaurus buried mid-meal with the last food still in its mouth. It got buried while it was eating. There is an Oviraptor fossilized while brooding over its eggs and still giving birth. Something happened instantaneously while these creatures were just living. Also, there's dinosaur trackways that abruptly end. This suggests these animals were overtaken suddenly.  

There's also these global sedimentary rock layers that they find in North America and Europe and North Africa. There's marine fossils on mountains. This is my favorite one. Marine fossils on mountains such as Mount Everest and the Himalayas and the Alps and the Rockies. They all contain marine fossils. What does this tell us? That they were once submerged underwater just as the Bible said. How on earth did these sea creatures get perched on top of these mountains hundreds of miles away from any large body of water? I suggest the easiest conclusion would be a global flood.

And also, we've talked about these mass fossil graveyards. There are huge collections of jumbled, mixed-species fossils, particularly in Wyoming and the Karoo basin in South Africa, and others in China.

Also, there are over 270 cultures around the globe who have flood legends. Think about that. 270 cultures around the globe who have flood legends. And they're striking parallels. They get kind of iffy on some of the minute details, but they all have the common theme. There's a divine judgment. There's a righteous man and his family who are spared. There's a large boat or vessel. The animals are saved and the rainbow is given as a covenant. Here's some of those. There's the Epic of Gilgamesh. It's similar to Noah's account, of course fabricated with mythology. There's other Sumerian tale of gods flooding the earth to control over a population. Even in Native American culture, the Hopi Apache and other tribes recount flood stories involving a man and his family being saved in a canoe and arriving on top of a mountain. In China, there's a tale of Nuwa—get that—repairing the heavens and the flood covering the land. In Greek, he is known as Nui. In Hinduism, the god Vishnu warns Manu, whose name translates to water or Noah, who survived a flood by building a large boat.  

And we see Noah's name go through all these different languages. In Latin, he's Nui. In Greek, he's Nui as well. In Hawaiian, he's Niu. In Chinese, he's Nuwa. Now how on earth did all these cultures end up with a similar story of a man with a similar name? They must have all come from one family. Whose family would that have been, I wonder? Probably Noah, Shem, Ham, and Japheth, if I was a betting man. Noah's name is remembered across cultures and this would not be possible if the flood were only a localized event affecting only a limited population. Rather, the flood was global. It impacted all of humanity and Shem, Ham, and Japheth had kids and children and grandchildren. They spread out. They repopulate the earth. They would carry the memory and the story with them. Of course, they spread over the whole globe.

Here's my strongest argument. Jesus and his apostles affirm the flood. And if you can't trust the words of Jesus, what are we even doing here? Jesus says in Matthew 24:37–39, "Just as it was in the days of Noah, men were eating, drinking, marrying, giving in marriage until the day the flood came and took them all away." And we have already studied 2 Peter 3, wherein Peter describes this global judgment—men perishing in the flood—and he draws a parallel to the coming judgment by fire.

Now here's some critiques I have of a local flood theory. If it's only a local flood, why would God tell Noah 120 years in advance to build an ark? Why wouldn't he just migrate somewhere else? That makes sense. If a lake is going to flood, we could just move somewhere else. Instead, the earth is going to flood. Let's build a boat.  

Also, there's God's promise in Genesis 9–11 never to flood the entire earth again. If it was a localized flood, then God would have lied. Because there have been many floods, devastating floods. If we go to Western North Carolina, we still see the mess it's made. It's not talking about a localized flood. This is a global flood.  

And also, the universal death of all creatures outside the ark makes no sense in the local context.

How did this happen? The Bible tells us that the flood waters and the windows of heaven were open. Now, the windows of heaven pour down rain from the sky for 40 days and 40 nights. We see the number 40 appear in Scripture multiple times as a symbol of judgment, of trial and testing. This relentless rainfall, without pause for 40 days and 40 nights, floods the land, and the springs of the great deep—massive underground water sources or ocean springs—burst forth.  

These springs, which are massive underground water sources or ocean springs, break forth. Together these sources create an overwhelming flood that covers the entire earth.

Did you know that today we have enough water to cover the entire earth if the earth were relatively smooth without large mountains? Think of the erosion washing away the soil, rocks, and plants. This would explain many of the canyons and sediment layers we find today. Also, there'd be topological changes—mountains pushed up or worn down, valleys carved deeper, and coastlines rearranged as the waters moved over the earth. There would also be massive shifting of the tectonic plates. This would uplift mountains like Ararat on which the ark finally rested. Remember Coley's reading Psalm 104:6 through 9? I'll read it again for you. "You covered the earth with the deep as with a garment. The water stood above the mountains. But notice the power of God. At your rebuke they fled. At the sound of your thunder they took flight. The mountains rose, the valleys sank down to the place you appointed for them. You set a boundary that they may not pass, so that they may not cover the earth again." Friends, that is a global flood. This Psalm echoes the flood story and shows how God's sovereign voice controls the waters—both in bringing judgment and in restraining the flood when the time comes.

Let's think about this now. How long were Noah and his family in the ark? Genesis 7:11 says the floodwaters began on the seventeenth day of the second month—this was day one inside the ark. Genesis 7:12 records that the rain fell for 40 days and 40 nights. The waters rose, they covered the highest mountain, and then the waters prevailed, and the ark floated. In chapter 7:24, the waters continued to rise for an additional 150 days—about five months—because the water came from the fountain of the great deep.  

But then the waters began to recede. Look in Genesis chapter 8, verse 1: "Then God remembered Noah and every living thing and all the animals that were with him in the ark. And God made a wind to pass over the earth, and the waters subsided. The fountains of the deep and the windows of heaven were stopped, and the rain from heaven was restrained, and the waters receded continually from the earth." At the end of the 150 days, the waters decreased. After 150 days, the water started to go down. In verse 5, on the first day of the tenth month, the waters rested on the mountains. The tops of the mountains were seen. Then Noah waited for the earth to dry—verses 6 through 7. Noah first sent out a raven, then he sent out a dove multiple times. Over the next several weeks, he would send this dove out and test if the earth was dry. Finally, the dove returned with an olive leaf on the 27th day of the second month. By the way, this is year two. On the 27th day of the second month, God told Noah to leave the ark.

Now that's the short condensed version of chapter 8. Let's break it down. How many days were they inside the ark? Well, second month, 17th day—day one, first year—the rains come. And then finally, on the first day of the tenth month, year one, the ark rests on Ararat. The 27th day of the second month, year two, they leave the ark. That totals 370 days inside the ark. 370 days. Could you imagine being in that ark for more than a year with your family and no one else? And all these smelly animals. This is hard work. There's chores to be done, animals to be fed, poop to clean up. All of this going on outside the ark, and you have no way of steering this vessel. Remember, there's no steering wheel in it. You are trusting God to take care of you, to see you safely through this flood, to deposit you on some mountain somewhere. Noah doesn't really know what's going on. He trusts the sovereign hand of God.

The good news is, chapter 8 verse 1, God remembers Noah. Now this doesn't mean that God had forgotten about him. Oh yeah, I forgot. There's eight people in this floating box. 370 days later, oh my bad, sorry I forgot about you. No. It's the same kind of remembering we see when God remembers his people suffering in the land of Egypt. It's the same remembering that God does with Hannah when she prays for a baby and he gives her Samuel. It's the same remembering that Jesus does with the thief on the cross when he says remember me when you come into your kingdom. It is God acting on behalf of his promise and bringing salvation.

Friends, God remembers His people. God never forgets you. He has invested so much in you that He will never leave you or forsake you. He remembers His promise and is faithful to His covenant. He never forgets. Praise God for His faithfulness.

Now imagine this: You're Noah. 300 or 255 days you've been rocking back and forth. You hear a big boom—“Whoa!”—you landed, we hit something. I hadn’t felt us move in a long time. Perhaps the water is decreasing. But, Lord, we’ve only got so much food. These animals are growing restless. Quite frankly, I am too. Lord, have You forgotten about us? Have You trapped us in here, sealed us in to die? No. Noah trusted that God had not forgotten him—God would not forsake him. Friends, let me tell you, even in your time of waiting, God has not forgotten you. In your time when your life feels like it’s rocking back and forth—“Lord, what is going on? Are You in control? Do You see me? Do You understand?”—yes, He does. His eye has never left you. In your weariness, in your weakness, even in your failing, God remembers you. He remembers the eternal covenant He’s made with you through His Son. The Bible says He numbers the very hair of our head. He collects our tears and the bottle.  

So even in our wondering and waiting and in our pain, God knows us. God remembers us. When we are going through the storms of life, God remembers us and we can be sure that He who began a good work in you will bring it to completion. Praise God for that.

The waters abate, Genesis 8 verse 1 through 14. Now, we've read parts of that passage. You can read it in full at home if you'd like. I'm going to give you the condensed version. The waters begin to recede, but we notice in chapter 8 something very profound—this narrative mirrors the creation story in Genesis chapter 1. How so? Because the Spirit of God hovered over the waters in the beginning. Do you remember that? Now, God causes the wind—remember, the same word for "spirit" and "wind"—to pass over the earth, and the earth begins to dry. The waters begin to subside, and then light emerges. The clouds break, and then dry land appears. Then vegetation starts to grow again. Does that not follow the creation pattern? Pretty awesome, isn't it? This is God recreating the earth using the same materials. This is God giving humanity a new beginning, a new start, and then eventually the animals and humans step onto the earth to fill it once more.

Friends, this is not just a reset. This is a re-creation. God is making something new out of the chaos. Now yes, the flood was an act of judgment, but here we see His grace restore what has been corrupted. This earth that had been filled with violence is now being cleansed. A new beginning is given to humanity. And then God commands him to come out of the ark. Verse 15: God spoke to Noah, saying, “Go out of the ark, you and your wife, and your sons and your sons’ wives with you. Bring out with you every living thing of all flesh that is with you—birds and cattle and every creeping thing that creeps on the earth—so that they may abound on the earth and be fruitful and multiply.” Noah steps out on the dry ground and he received the same command that Adam did. This creation mandate—“be fruitful and multiply.” What does this teach us? Even though the fall has happened and the flood has come, God is not done with His creation or with us. God is doing something new. He is offering humanity a new start.

But friends, in Christ, humanity is offered the ultimate new start. If any man is in Christ, he is a new creation. The old is gone; behold, the new has come. Friends, it's Jesus Christ who brings us safely through the waters of death and gives us new life. Regardless of your past, regardless of your sins, he can forgive you, he can make you new. You can have a new start, a new beginning, and be born again. You were born a sinner, like Adam, but you can be reborn as a child of God. He can give you a new nature, a new heart, and a new identity as sons and daughters of the Most High.

Now, I just want to go through and pick up some really cool details here in chapter 8, some details that we don't need to miss. Verse 4 says, the ark rested in the seventh month, the 17th day of the month on the mountains of Ararat. Now here's a question: do you guys think that the ark has been discovered? I think there's a strong possibility, and I think we have a photo if y'all can pull it up and put it on the screen. In 1959, there's a Turkish army captain, last name Drupinar, who identified a boat-shaped formation approximately 18 miles south of Mount Ararat. The dimensions of this structure are very similar to the dimensions of Noah's Ark given in the book of Genesis.  

They've also used ground-penetrating radar analysis in 2025. Researchers from the Noah's Ark Scans project reported discovering angular structures, a central tunnel, and multiple layers—three layers to be exact—resembling the decks of a ship within this formation. How about that? They've done soil analysis, and these tests reveal higher organic content and higher potassium levels, suggesting the presence of decayed wood. There's also vegetation patterns, distinct grass coloration within the formation, indicating that this was possibly a man-made structure. But also, it's interesting that this is Mount Ararat, the exact same mountain that the Bible says the ark came to rest upon.

Now, due to the mountain's remote location, harsh weather conditions, and political sensitivities, they don't want people poking around up there. But as we all know, when you tell people there's a line not to cross, guess what? Someone's going to cross it. They even dove into it—and guess what? They found beams, decking, and a central hole much like a ship.  

Researchers from the Mount Ararat and Noah's Ark research team reported finding marine deposits, shellfish remnants, and clay-like materials dating between 3,500 and 5,000 years ago. Guess what? That aligns perfectly with the timing of Noah's Flood. It's pretty cool.

Let's talk about the ark's landing. Now, when did it come to rest? Verse 4 tells us it came to rest on the 17th day of the month. Now you might think it's just a date, the 17th day of the month. Did you know that this calendar date has high significance in the Bible? I'm going to give you some events that happened on this calendar day—not this year obviously, but the calendar day of the 17th day of the month. Well, in Exodus 12:1, God changes the Israelite calendar so that what was the seventh month became their first month. The Jews today still use two calendars—this is not confusing at all. So, why is this significant? Well, that's the Jewish feast of first fruits, which symbolizes new life. It's celebrated on the first Sunday after Passover. Remember, Passover celebrates being delivered from Egypt. Three days later, they celebrate new life. Also, Israel crossed the Red Sea on the 17th day of this month. They left behind slavery and death, the drowning Egyptians, and they stepped into the new life God has for them.  

Manna ceased on the 16th day of this month, and on the 17th day Israel ate the new grain of the promised land 40 years later.

Well, fast forward hundreds of years from that—we come to the book of Esther. Esther proclaims a fast on the 14th, 15th, and 16th day, and on the 17th day, Esther approaches the king. God overturns the plot of the enemy, Haman, to destroy the Jews. This leads to the greatest 17th of all. Now, if Jesus died on the 14th on Passover, he was crucified as the perfect Passover Lamb—meaning he rose on the 17th day. All these 17th days before the flood: humanity had grown so corrupt, God sends a flood. It looks like the serpent had won. God brings judgment, but humanity is spared and given a new start through knowing his family. Before crossing the Red Sea years later, Israel seemed trapped and doomed—but God brings resurrection life to his people and death to his enemies.  

Before Esther approached the king on the 17th, it looked like the Jews would be destroyed by Haman—but Haman instead is defeated. When Jesus died on the 14th, it looked like all hope was lost. Till the 17th day—until Easter Sunday morning—he rises from the grave. He defeats death, hell, sin, and Satan—and he brings new life and a new beginning to God’s people. Is it a coincidence that all these events happen on the same 17th? I think not. God is far too wise and far too organized to do that.

Now Noah, he leaves the ark. He sends out a dove, and the dove eventually returns with an olive leaf—meaning that life has returned to the earth. But who descends upon Jesus in the form of a dove at his baptism? It is the Holy Spirit. So what is Jesus doing? He is the better and greater Noah. This Holy Spirit descending in the form of a dove announces the arrival of one who brings true and lasting rest, hope, and new life.  

Then, when the Lord gives the word, Noah and his family step out onto a new earth, and God reaffirms the same creation mandate he gave to Adam: "Be fruitful, multiply, fill the earth." Friend, this is not just the dawning of a new day for Noah. This is the dawning of a new day for all of humanity. This was mercy for all of us. Judgment has passed, mercy and grace have triumphed, and a new beginning had come.

Now let's look in verse 20 and we'll finish up. Chapter 8 verse 20, then Noah built an altar to the Lord and took of every clean animal and every clean bird and offered burnt offerings on the altar and the Lord smelled a soothing aroma and the Lord said in his heart I will never again curse the ground for man's sake although the imagination of man's heart is evil from his youth nor will I again destroy every living thing as I have done while the earth remains seed time and harvest cold and heat winter and summer and day and night shall not cease. What's the very first thing Noah does when he exits the ark? Does he get a rock and hold it in his hand? Does he kiss the dirt like "oh I missed you, land, earth"? No. He doesn't do something practical like plow a field and plant a garden or build a house or somehow forage for food. Even though the entire human race existence rests upon his family, no—he does what matters most. He builds an altar and he worships the God who spared him and his family's life. Noah, his priority is worship. His priority is God. God is always first. Worship is always first.  

And he leads his family in corporate worship, friends. What is first in your life? Is God number one? Have you praised him and thanked him for saving you? Are you leading your family in corporate worship? Are the things of God and the things of eternity a priority to you?

So Noah offers to God these clean animals. This is long before the Mosaic law, but he understands that you give God your first and your best. He’s worthy of reverent worship, and the Bible says God was pleased. He smelled the aroma. He received it. God’s acceptance of the sacrifice indicates that judgment had passed. Judgment has passed, but it points us forward to the greater sacrifice that God would make in giving us His Son, Jesus Christ, the Lamb without blemish, who offered Himself. As Ephesians 5:2 says, as a sacrifice that’s pleasing to God. And because of His ultimate sacrifice, judgment is passed. We are no longer under condemnation. Judgment has fallen upon another in our place. Isaiah 53:11 says, God will see the travail of His soul and be satisfied. So what happened at the cross? At the cross, Christ bore the full weight of your sin and mine, and endured the wrath of God in our place as our substitute. His suffering accomplished exactly what it intended—the salvation of all His elect. Christ offered Himself as a sacrifice to God, and it’s through His atoning death that justice was satisfied and mercy was poured out on undeserving sinners. The travail of His soul was not meaningless, friends. It was the price of our redemption, and it satisfied God. And it brings many sons to glory.  

Then, after Noah’s sacrifice, God makes a covenant. He promises never again to destroy the earth in this way, never again to wipe humanity from the face of the earth. This is a new beginning. This is—[I’m gonna end with this]—no one, this family, step out of the ark. This is a new chapter in human history. This is a new chance for humanity. And I asked you last week, but I’m gonna ask you again: Do you ever wish that you could start over? Do you ever wish that you could take back all your mistakes and they would be erased? Have you ever said something that you wish you could take back? Have you ever longed for a new beginning, friends? The good news of the gospel is that a new beginning is found in the Lord Jesus Christ. All of your sin can be washed away. The curse of sin and its condemnation is undone. Our sins can be removed from us forever, cast as far away as the East is from the West. He justifies us and He makes us right in the eyes of a holy God. I love what Spurgeon said: If our sins be like mountains, His love shall be like Noah’s flood. I’ll know about you, but I have a mountain of sin that I need leveled and washed away. Praise God that His blood washes away every sin, removes every stain, removes even the guilt of our conscience. And He gives us a new heart. He gives us a new beginning. We call this being born again. So as they come and give us a hymn of invitation this morning, perhaps you need this new beginning. Christ has suffered and died in your place. When He cried, “It is finished,” that means it is finished. There’s nothing for you to add to or take away from the work of God. You repent of your sins. You place your faith in the Lord Jesus Christ, and He makes you a child of God. He gives you new life, eternal life. This altar is open.
"""

prompt = prompt.format(SERMON_TEXT=sermon)

p2 = """
you are a senior meta prompt engineer. write a prompt that will take a provided text of a sermon and get bible refereces from that text. Then take another persona of a grumpy old veteran senior prompt engineer and really trash that prompt and give demands for improvement. then the first persona can go back and fix the errors, and present the new prompt to the company CTO for review. the CTO persona should look for areas that the end user would want and suggest these changes. Finally, the first persona will take all that feedback and gie me the final prompt.
"""
client = OllamaClient(temperature=1.0)
response = client.submit_prompt(p2)
print(response)

client = OllamaClient(temperature=0.0)
response = client.submit_prompt(p2)
print(response)

client = OllamaClient(temperature=0.5)
response = client.submit_prompt(p2)
print(response)